/* ===== ĐẤU TRƯỜNG v3 — BẢN ĐỒ TRẬN ĐẤU THỰC =====
   Trận đấu diễn ra trên một scene canvas riêng, không phải hộp log giả lập.
   - Thách đấu -> chuyển thẳng vào bản đồ đấu trường.
   - Hai nhân vật di chuyển, áp sát, ra đòn, hiệu ứng, sát thương, HP.
   - Pause / tốc độ / bỏ qua.
   - Sau trận mới hiện kết quả + xem lại.
   - Không đụng Base64/assets của game chính.
   - Đây vẫn là PvE/local simulation; backend PvP chưa được nối.
*/
(function(){
'use strict';
var KEY='kthm2_arena_v3',root=null,canvas=null,ctx=null,raf=0,state=null,busy=false,token=0,current=null,paused=false,speed=1,startedAt=0,elapsed=0,logLines=[];
var W=0,H=0,DPR=1;
function esc(s){return String(s==null?'':s).replace(/[&<>"']/g,function(c){return({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'})[c]})}
function load(){try{state=JSON.parse(localStorage.getItem(KEY)||'null')}catch(e){state=null}if(!state||typeof state!=='object')state={points:1000,wins:0,losses:0,streak:0,season:1,day:'',today:0,lastBattle:null};var d=new Date().toISOString().slice(0,10);if(state.day!==d){state.day=d;state.today=0;state.day=d;save()}}
function save(){try{localStorage.setItem(KEY,JSON.stringify(state))}catch(e){}}
function power(){try{return Math.max(1,Math.round((typeof atk==='function'?atk():100)*5+(typeof df==='function'?df():50)*.55+(typeof mx==='function'?mx():500)*.08))}catch(e){return 100}}
function pname(){try{return (typeof PS!=='undefined'&&PS[cur]&&(PS[cur].nm||PS[cur].name))||(typeof pn!=='undefined'&&pn)||'Đạo Hữu'}catch(e){return 'Đạo Hữu'}}
function realm(){try{return typeof ZC!=='undefined'&&ZC.nm?ZC.nm():'Tu sĩ'}catch(e){return 'Tu sĩ'}}
function opponents(){var p=power(),base=Math.max(300,p),names=['Huyền Vũ Kiếm Tôn','Thanh Liên Tiên Tử','Ma Đạo Cuồng Nhân','Thiên Cơ Đạo Nhân','U Minh Thánh Nữ','Cửu Thiên Kiếm Khách'],out=[];for(var i=0;i<5;i++){var mul=.84+i*.08+(Math.random()-.5)*.08;out.push({id:i,n:names[(i+state.season)%names.length],pw:Math.max(100,Math.round(base*mul)),lv:Math.max(1,Math.round((typeof P!=='undefined'&&P.lv||1)*(0.9+i*.04))),rank:Math.max(1,Math.round(50+i*18))})}return out}
function makeBattle(me,op){var mh=Math.max(100,typeof mx==='function'?mx():500),oh=Math.max(100,Math.round(mh*(op.pw/me.pw)*(.85+Math.random()*.3))),ma=Math.max(1,me*.18),oa=Math.max(1,op.pw*.18),mr=mh,or=oh,round=0,events=[];while(mr>0&&or>0&&round<18){round++;var first=round%2===1,md=Math.max(1,Math.round(ma*(.72+Math.random()*.45))),od=Math.max(1,Math.round(oa*(.72+Math.random()*.45)));if(first){or-=md;events.push({r:round,side:'me',d:md,me:Math.max(0,mr),op:Math.max(0,or),text:pname()+' tung kiếm quyết, gây '+md+' sát thương!'});if(or<=0)break;mr-=od;events.push({r:round,side:'op',d:od,me:Math.max(0,mr),op:Math.max(0,or),text:op.n+' phản kích, gây '+od+' sát thương!'});}else{mr-=od;events.push({r:round,side:'op',d:od,me:Math.max(0,mr),op:Math.max(0,or),text:op.n+' tung pháp quyết, gây '+od+' sát thương!'});if(mr<=0)break;or-=md;events.push({r:round,side:'me',d:md,me:Math.max(0,mr),op:Math.max(0,or),text:pname()+' phản công, gây '+md+' sát thương!'});}}return{win:or<=0,round:round,meMax:mh,opMax:oh,events:events,meHp:Math.max(0,mr),opHp:Math.max(0,or)}}
function reward(win){var pts=win?18:7;state.points=Math.max(0,state.points+(win?pts:-12));if(win){state.wins++;state.streak++;try{gold=(gold|0)+250+state.streak*20;frag=(frag|0)+(state.streak%3===0?1:0)}catch(e){}}else{state.losses++;state.streak=0}state.today++;state.last=Date.now();save();try{if(typeof sv==='function')sv()}catch(e){}return pts}
function rank(){return Math.max(1,Math.round(1200-Math.max(0,state.points-1000)*.9))}
function stop(){if(raf){cancelAnimationFrame(raf);raf=0}}
function resize(){if(!canvas)return;DPR=Math.min(window.devicePixelRatio||1,2);W=canvas.clientWidth;H=canvas.clientHeight;canvas.width=Math.max(1,Math.round(W*DPR));canvas.height=Math.max(1,Math.round(H*DPR));ctx=canvas.getContext('2d');ctx.setTransform(DPR,0,0,DPR,0,0)}
function rnd(n){return Math.sin(n*12.9898)*43758.5453%1}
function rr(x,y,w,h,r){w=Math.max(0,Number(w)||0);h=Math.max(0,Number(h)||0);r=Math.max(0,Number(r)||0);var q=Math.min(r,w/2,h/2);ctx.beginPath();ctx.moveTo(x+q,y);ctx.arcTo(x+w,y,x+w,y+h,q);ctx.arcTo(x+w,y+h,x,y+h,q);ctx.arcTo(x,y+h,x,y,q);ctx.arcTo(x,y,x+w,y,q);ctx.closePath()}
function text(t,x,y,size,col,align){ctx.fillStyle=col||'#fff';ctx.font='600 '+size+'px system-ui,-apple-system,Segoe UI,sans-serif';ctx.textAlign=align||'center';ctx.textBaseline='middle';ctx.fillText(t,x,y)}
function glowCircle(x,y,r,col,a){var g=ctx.createRadialGradient(x,y,0,x,y,r);g.addColorStop(0,col.replace(')',','+a+')').replace('rgb','rgba'));g.addColorStop(1,'rgba(0,0,0,0)');ctx.fillStyle=g;ctx.beginPath();ctx.arc(x,y,r,0,Math.PI*2);ctx.fill()}
function drawBackground(t){var g=ctx.createLinearGradient(0,0,0,H);g.addColorStop(0,'#090d1a');g.addColorStop(.52,'#20161b');g.addColorStop(1,'#080606');ctx.fillStyle=g;ctx.fillRect(0,0,W,H);
  // moon and clouds
  ctx.fillStyle='rgba(232,208,160,.13)';ctx.beginPath();ctx.arc(W*.76,H*.18,Math.min(W,H)*.09,0,Math.PI*2);ctx.fill();
  for(var i=0;i<9;i++){var x=((i*173+t*.01*(i%2?1:-1))%(W+180))-90,y=H*(.12+(i%3)*.055);ctx.fillStyle='rgba(115,96,111,.16)';ctx.beginPath();ctx.ellipse(x,y,95,18,0,0,Math.PI*2);ctx.fill()}
  // mountain silhouette
  ctx.fillStyle='#15111b';ctx.beginPath();ctx.moveTo(0,H*.53);for(var x=0;x<=W;x+=60){var yy=H*(.46+Math.abs(Math.sin(x*.018))*-.11);ctx.lineTo(x,yy)}ctx.lineTo(W,H*.62);ctx.lineTo(0,H*.62);ctx.closePath();ctx.fill();
  // spectator stands
  ctx.fillStyle='#0c0a0b';ctx.fillRect(0,H*.37,W,H*.25);for(var row=0;row<4;row++){ctx.strokeStyle='rgba(191,143,71,.18)';ctx.lineWidth=1;ctx.beginPath();ctx.moveTo(0,H*(.39+row*.045));ctx.lineTo(W,H*(.39+row*.045));ctx.stroke();for(var j=0;j<Math.ceil(W/32);j++){var xx=j*32+((row%2)*12);ctx.fillStyle=['#6b3940','#6d5b37','#3d5064','#573a62'][(j+row)%4];ctx.beginPath();ctx.arc(xx,H*(.385+row*.045),4,0,Math.PI*2);ctx.fill()}}
  // giant gate
  var gx=W/2,gy=H*.34;ctx.fillStyle='#241a18';ctx.fillRect(gx-70,gy-80,140,90);ctx.fillStyle='#090708';ctx.beginPath();ctx.arc(gx,gy+8,48,Math.PI,0);ctx.lineTo(gx+48,gy+10);ctx.lineTo(gx-48,gy+10);ctx.closePath();ctx.fill();text('⚔',gx,gy-28,30,'#d8ad59');
  // arena floor
  var fy=H*.70, rx=W*.43, ry=H*.20;ctx.fillStyle='#38251e';ctx.beginPath();ctx.ellipse(W/2,fy,rx,ry,0,0,Math.PI*2);ctx.fill();ctx.strokeStyle='#9c7038';ctx.lineWidth=3;ctx.stroke();ctx.strokeStyle='rgba(215,175,91,.28)';ctx.lineWidth=2;ctx.beginPath();ctx.ellipse(W/2,fy,rx*.78,ry*.72,0,0,Math.PI*2);ctx.stroke();ctx.beginPath();ctx.arc(W/2,fy,Math.min(rx,ry)*.55,0,Math.PI*2);ctx.stroke();
  // stone tiles
  for(var k=0;k<26;k++){var tx=(k*71)%W,ty=H*.59+((k*37)%Math.max(80,H*.26));ctx.strokeStyle='rgba(255,220,150,.07)';ctx.beginPath();ctx.moveTo(tx,ty);ctx.lineTo(tx+42,ty+7);ctx.stroke()}
  // torches
  for(var q=0;q<4;q++){var tx2=45+q*(W-90)/3;ctx.strokeStyle='#624322';ctx.lineWidth=5;ctx.beginPath();ctx.moveTo(tx2,H*.62);ctx.lineTo(tx2,H*.44);ctx.stroke();var pulse=12+Math.sin(t*.01+q)*3;glowCircle(tx2,H*.43,pulse,'rgb(255,150,45)',.18);text('🔥',tx2,H*.43,22,'#ffb34e')}
}
function fighter(x,y,side,hp,maxhp,flash,move,attack,name){ctx.save();ctx.translate(x,y);var dir=side==='me'?1:-1, bob=Math.sin(move*.012)*3;ctx.translate(0,bob);if(attack>0){ctx.rotate(dir*.12*Math.sin(attack*Math.PI))}
  // aura
  var ac=side==='me'?'#55b7ff':'#e85b68';var gr=ctx.createRadialGradient(0,-55,4,0,-55,62);gr.addColorStop(0,ac+'88');gr.addColorStop(1,'rgba(0,0,0,0)');ctx.fillStyle=gr;ctx.beginPath();ctx.arc(0,-50,64,0,Math.PI*2);ctx.fill();
  // shadow
  ctx.fillStyle='rgba(0,0,0,.45)';ctx.beginPath();ctx.ellipse(0,7,42,11,0,0,Math.PI*2);ctx.fill();
  // robe/body
  ctx.fillStyle=side==='me'?'#244e72':'#692b32';ctx.beginPath();ctx.moveTo(-22,-58);ctx.lineTo(22,-58);ctx.lineTo(34,5);ctx.lineTo(-34,5);ctx.closePath();ctx.fill();ctx.strokeStyle='#d4a65a';ctx.lineWidth=2;ctx.stroke();
  // head
  ctx.fillStyle='#e5b89a';ctx.beginPath();ctx.arc(0,-75,17,0,Math.PI*2);ctx.fill();ctx.fillStyle=side==='me'?'#172b3a':'#2a1114';ctx.beginPath();ctx.arc(0,-82,19,Math.PI,Math.PI*2);ctx.fill();
  // legs
  ctx.strokeStyle='#15161b';ctx.lineWidth=10;ctx.beginPath();ctx.moveTo(-10,3);ctx.lineTo(-16,28);ctx.moveTo(10,3);ctx.lineTo(16,28);ctx.stroke();
  // weapon
  ctx.strokeStyle='#e9d6a3';ctx.lineWidth=5;ctx.beginPath();ctx.moveTo(dir*18,-28);ctx.lineTo(dir*(attack>0?70:44),-62);ctx.stroke();ctx.strokeStyle='#fff4c8';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(dir*18,-28);ctx.lineTo(dir*(attack>0?70:44),-62);ctx.stroke();
  if(flash>0){ctx.globalAlpha=Math.min(.75,flash);ctx.fillStyle='#fff';ctx.beginPath();ctx.arc(0,-45,55,0,Math.PI*2);ctx.fill()}
  ctx.restore();
  // hp bar
  var bw=Math.min(210,W*.28),bx=x-bw/2,by=y-132;ctx.fillStyle='rgba(0,0,0,.65)';rr(bx,by,bw,13,7);ctx.fill();ctx.fillStyle=side==='me'?'#55c9ff':'#e85c67';rr(bx+2,by+2,(bw-4)*Math.max(0,hp/maxhp),9,5);ctx.fill();ctx.strokeStyle='#b8934d';ctx.lineWidth=1;ctx.stroke();text(name,x,by-13,12,'#f2dfb0');text(Math.max(0,Math.round(hp))+' / '+Math.round(maxhp),x,by+6,9,'#fff');
}
function slash(x,y,dir,p){ctx.save();ctx.translate(x,y);ctx.strokeStyle=p<.5?'#fff2a0':'#79d7ff';ctx.lineWidth=5;ctx.globalAlpha=Math.sin(Math.min(1,p)*Math.PI);ctx.beginPath();ctx.arc(0,0,46,-1.3*dir,1.0*dir);ctx.stroke();ctx.restore()}
function fireball(x,y,dir,p,col){ctx.save();var xx=x+dir*p*130,yy=y-65-Math.sin(p*Math.PI)*28;glowCircle(xx,yy,26,col,.35);ctx.fillStyle='#fff4bf';ctx.beginPath();ctx.arc(xx,yy,8,0,Math.PI*2);ctx.fill();ctx.restore()}
function drawHUD(b,op,evIndex){ctx.fillStyle='rgba(5,5,7,.74)';ctx.fillRect(0,0,W,62);text('⚔️ ĐẤU TRƯỜNG',18,20,15,'#e9c46a','left');text('Vòng '+Math.ceil((evIndex+1)/2)+' / '+Math.max(1,b.round),18,43,11,'#cdbd9b','left');text(pname(),W*.25,20,13,'#8ed9ff');text(op.n,W*.75,20,13,'#ff9b91');text('●',W*.5,20,10,'#e9c46a');text(paused?'⏸ TẠM DỪNG':'Đang giao chiến',W/2,43,11,paused?'#ffd36a':'#a9dcae');
  ctx.fillStyle='rgba(4,4,6,.82)';ctx.fillRect(0,H-64,W,64);text('Tốc độ',58,H-43,10,'#cdbd9b');[1,2,4].forEach(function(v,i){var x=102+i*43;rr(x,H-55,36,24,6);ctx.fillStyle=speed===v?'#8a6224':'#30271d';ctx.fill();ctx.strokeStyle='#a8864e';ctx.stroke();text(v+'×',x+18,H-43,11,'#fff')});rr(W-155,H-55,65,24,6);ctx.fillStyle=paused?'#71531f':'#30271d';ctx.fill();ctx.strokeStyle='#a8864e';ctx.stroke();text(paused?'▶':'⏸',W-122,H-43,12,'#fff');rr(W-82,H-55,65,24,6);ctx.fillStyle='#30271d';ctx.fill();ctx.strokeStyle='#a8864e';ctx.stroke();text('⏭ Bỏ qua',W-49,H-43,10,'#fff');
  if(logLines.length){var last=logLines[logLines.length-1];rr(W/2-Math.min(330,W*.42),H*.72,Math.min(660,W*.84),36,10);ctx.fillStyle='rgba(8,5,4,.72)';ctx.fill();text(last,W/2,H*.72+18,12,last.indexOf('phản')>=0?'#ffaaa0':'#b9edc5')}
}
function hitFlash(side){return side==='me'?0:0}
function renderFrame(now){if(!root||!canvas||!current)return;var b=current.b,op=current.op;elapsed=now-startedAt;var t=elapsed/1000*speed,events=b.events,idx=0;while(idx<events.length&&events[idx].at<=t)idx++;var evIndex=Math.min(events.length,idx);var frac=0;if(idx<events.length){var ev=events[idx],prev=idx?events[idx-1]:null;var base=prev?prev.at:0;frac=Math.max(0,Math.min(1,(t-base)/(ev.at-base||1)))}
  drawBackground(now);var e=evIndex?events[evIndex-1]:null;var prev=evIndex>1?events[evIndex-2]:null;var meHp=evIndex?events[evIndex-1].me:b.meMax,opHp=evIndex?events[evIndex-1].op:b.opMax;
  var phase=e?Math.min(1,(t-e.at)/.42):0, meBase=W*.30,opBase=W*.70,approach=Math.min(1,t/.9);var mx=meBase+(W*.08)*approach,ox=opBase-(W*.08)*approach;var atkMe=e&&e.side==='me'?Math.max(0,1-phase):0,atkOp=e&&e.side==='op'?Math.max(0,1-phase):0;fighter(mx,H*.70,'me',meHp,b.meMax,atkMe,now,atkMe,pname());fighter(ox,H*.70,'op',opHp,b.opMax,atkOp,now,atkOp,op.n);
  if(atkMe>0)slash(mx+18,H*.70-50,1,1-atkMe);if(atkOp>0)slash(ox-18,H*.70-50,-1,1-atkOp);if(e&&e.side==='me'&&phase<.8)fireball(mx+20,H*.70,1,Math.min(1,phase/.8),'rgb(80,190,255)');if(e&&e.side==='op'&&phase<.8)fireball(ox-20,H*.70,-1,Math.min(1,phase/.8),'rgb(255,85,100)');
  drawHUD(b,op,evIndex);if(evIndex>0&&(!logLines.length||logLines.length<evIndex)){for(var j=logLines.length;j<evIndex;j++)logLines.push(events[j].text);if(logLines.length>3)logLines=logLines.slice(-3)}
  if(evIndex>=events.length&&t>events[events.length-1].at+1.2){finishBattle();return}raf=requestAnimationFrame(renderFrame)
}
function prepareEvents(b){var t=1.2;b.events.forEach(function(e){e.at=t;t+=.9})}
function showScene(op,b,isReplay){stop();root.classList.add('on');resize();root.classList.remove('result');var panel=root.querySelector('.arena-result');if(panel)panel.style.display='none';paused=false;speed=1;elapsed=0;logLines=[];current={op:op,b:b,isReplay:!!isReplay};prepareEvents(b);startedAt=performance.now();raf=requestAnimationFrame(renderFrame)}
function finishBattle(){if(!current)return;stop();busy=false;var op=current.op,b=current.b,isReplay=current.isReplay;var pts=isReplay&&state.lastBattle?state.lastBattle.pts:reward(b.win);if(!isReplay){state.lastBattle={op:op,win:b.win,events:b.events,meMax:b.meMax,opMax:b.opMax,pts:pts,at:Date.now()};save()}showResult(op,b,pts,isReplay)}
function showResult(op,b,pts,isReplay){root.classList.add('result');var panel=root.querySelector('.arena-result');if(panel)panel.style.display='flex';var panel=root.querySelector('.arena-result');panel.innerHTML='<div class="result-card"><div class="result-title '+(b.win?'win':'lose')+'">'+(b.win?'🏆 CHIẾN THẮNG':'💀 THẤT BẠI')+'</div><div class="result-line"><b>'+esc(pname())+'</b> ⚔️ <b>'+esc(op.n)+'</b></div><div class="result-sub">'+(isReplay?'🔄 Xem lại — không nhận lại thưởng':(b.win?'+'+pts+' điểm · 🎁 Phần thưởng đã nhận':'-12 điểm · thử lại lần sau'))+'</div><div class="result-log">'+b.events.map(function(e){return '<div>'+esc('Lượt '+e.r+': '+e.text)+'</div>'}).join('')+'</div><div class="result-actions"><button id="arena-result-back">↩ Đấu Trường</button><button id="arena-result-replay">🔄 Xem lại trận</button></div></div>';root.querySelector('#arena-result-back').onclick=function(){root.classList.remove('result');openLobby()};root.querySelector('#arena-result-replay').onclick=function(){root.classList.remove('result');showScene(op,b,true)};}
function build(){root=document.createElement('div');root.id='arena-scene';root.innerHTML='<canvas id="arena-canvas"></canvas><div class="arena-topbar"><button id="arena-exit">✕ Rời đấu trường</button><span>⚔️ Đấu Trường Linh Giới</span><span id="arena-mini">'+esc(realm())+'</span></div><div class="arena-result"></div>';document.body.appendChild(root);canvas=root.querySelector('#arena-canvas');ctx=canvas.getContext('2d');root.querySelector('#arena-exit').onclick=function(){if(busy&&!confirm('Rời trận? Trận này sẽ không nhận thưởng.'))return;busy=false;current=null;stop();root.classList.remove('on','result')};window.addEventListener('resize',resize);resize();canvas.addEventListener('click',function(e){var r=canvas.getBoundingClientRect(),x=e.clientX-r.left,y=e.clientY-r.top;if(y>H-70){if(x>W-95){if(current){current.skip=true;finishBattle()}}else if(x>W-170){paused=!paused;if(!paused){startedAt=performance.now()-elapsed/speed}}else if(x>80&&x<235){var idx=Math.round((x-102)/43),vals=[1,2,4];if(vals[idx]){var old=speed;speed=vals[idx];if(!paused)startedAt=performance.now()-elapsed*old/speed}}}});}
function open(){load();if(!root)build();root.classList.remove('result');root.classList.add('on');resize();busy=false;openLobby()}
function openLobby(){load();root.classList.remove('result');var c=root.querySelector('.arena-result');c.style.display='flex';c.innerHTML='<div class="arena-lobby"><div class="lobby-title">⚔️ ĐẤU TRƯỜNG LINH GIỚI</div><div class="lobby-info"><b>'+esc(pname())+'</b><br><small>'+esc(realm())+' · Lực chiến '+power().toLocaleString()+' · Điểm '+state.points+' · Hạng #'+rank()+'</small><br><small>🏆 '+state.wins+' thắng · '+state.losses+' thua · 🔥 Chuỗi '+state.streak+' · Lượt hôm nay '+Math.max(0,10-(state.today|0))+'/10</small></div><div id="arena-opps"></div><div class="lobby-note">Chọn đối thủ rồi bấm <b>⚔️ THÁCH ĐẤU</b>. Bạn sẽ chuyển thẳng vào <b>bản đồ đấu trường</b> và trận đánh bắt đầu ngay.</div></div>';var ops=opponents(),left=Math.max(0,10-(state.today|0)),list=root.querySelector('#arena-opps');list.innerHTML=ops.map(function(o){return '<div class="arena-op"><div><b>'+esc(o.n)+'</b><small>Lv '+o.lv+' · Lực chiến '+o.pw.toLocaleString()+' · Hạng #'+o.rank+'</small></div><button data-id="'+o.id+'" '+(left<=0?'disabled':'')+'>⚔️ THÁCH ĐẤU</button></div>'}).join('');list.querySelectorAll('button[data-id]').forEach(function(btn){btn.onclick=function(){challenge(+btn.getAttribute('data-id'))}});}
function challenge(id){load();if(busy)return;if(state.today>=10){alert('Đã hết 10 lượt Đấu Trường hôm nay.');return}var o=opponents().find(function(x){return x.id==id});if(!o)return;var b=makeBattle(power(),o);busy=true;token++;current={op:o,b:b,isReplay:false};showScene(o,b,false)}
function close(){busy=false;current=null;stop();if(root)root.classList.remove('on','result')}
window.Arena={open:open,close:close,save:save,load:load,api:{challenge:challenge}};
function addButton(){if(document.getElementById('arena-btn'))return;var b=document.createElement('button');b.id='arena-btn';b.className='sb';b.title='Đấu Trường';b.innerHTML='⚔️<small>Đấu</small>';b.onclick=open;document.body.appendChild(b)}
function styles(){if(document.getElementById('arena-v3-style'))return;var st=document.createElement('style');st.id='arena-v3-style';st.textContent=`#arena-scene{position:fixed;inset:0;z-index:99999;display:none;background:#080606;font-family:system-ui,-apple-system,Segoe UI,sans-serif;color:#fff}#arena-scene.on{display:block}#arena-canvas{position:absolute;inset:0;width:100%;height:100%;touch-action:none}#arena-scene .arena-topbar{position:absolute;top:0;left:0;right:0;height:44px;display:flex;align-items:center;justify-content:space-between;padding:0 10px;background:linear-gradient(180deg,rgba(7,7,10,.9),rgba(7,7,10,.2));font-size:13px;color:#e9d39c;pointer-events:none}#arena-exit{pointer-events:auto;background:rgba(45,31,20,.85);border:1px solid #9e793e;border-radius:6px;color:#f2e4bd;padding:6px 9px;font:inherit}.arena-result{position:absolute;inset:0;display:flex;align-items:center;justify-content:center;background:rgba(0,0,0,.62);padding:18px}.arena-result .result-card{width:min(620px,92vw);max-height:82vh;overflow:auto;background:linear-gradient(180deg,#1b120d,#0c0908);border:1px solid #b08a49;border-radius:12px;box-shadow:0 20px 80px #000;padding:18px}.arena-result .result-title{text-align:center;font-size:24px;font-weight:800;margin-bottom:10px}.arena-result .win{color:#ffd86a}.arena-result .lose{color:#ff9188}.result-line{text-align:center;color:#e9d8b1}.result-sub{text-align:center;margin:9px 0;color:#c9b997}.result-log{background:#080605;border-radius:8px;padding:10px;font-size:11px;line-height:1.55;max-height:180px;overflow:auto}.result-actions{display:flex;justify-content:center;gap:8px;margin-top:12px}.result-actions button,.arena-op button{background:#5c431f;color:#f5e7be;border:1px solid #b18b4c;border-radius:6px;padding:8px 12px;font:inherit}.arena-result{z-index:5}.arena-lobby{position:absolute;left:50%;top:50%;transform:translate(-50%,-50%);width:min(620px,94vw);max-height:84vh;overflow:auto;background:rgba(16,10,8,.95);border:1px solid #b18b4c;border-radius:12px;padding:16px;box-shadow:0 20px 90px #000}.lobby-title{text-align:center;font-size:20px;font-weight:800;color:#ffd86a;margin-bottom:10px}.lobby-info{text-align:center;line-height:1.55;color:#e9d9b6;margin-bottom:10px}.arena-op{display:flex;justify-content:space-between;gap:10px;align-items:center;background:#19100c;border:1px solid #5c4327;border-radius:8px;padding:9px;margin:7px 0}.arena-op b{display:block}.arena-op small{display:block;color:#bcae91;margin-top:3px}.arena-op button{white-space:nowrap}.arena-op button:disabled{opacity:.45}.lobby-note{text-align:center;font-size:11px;color:#bcae91;margin-top:10px;line-height:1.5}@media(max-width:640px){.arena-topbar span:nth-child(2){font-size:12px}.arena-topbar span:nth-child(3){display:none}.arena-lobby{padding:12px}.arena-op{padding:8px}.arena-op button{padding:7px 9px;font-size:11px}}`;document.head.appendChild(st)}
function init(){load();styles();addButton()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();
