/* ===== ĐẤU TRƯỜNG v4 — NHÂN VẬT + SKILL THẬT =====
   - Dùng sprite/ảnh nhân vật thật đã có trong game (RIGI).
   - Dùng bộ kỹ năng thật từ CHR/PS/skill data của engine.
   - Skill damage lấy multiplier thật k[5]; tên/icon/cost/cooldown lấy trực tiếp từ skill.
   - Trận đấu là local/PvE simulation; chưa phải server-authoritative PvP.
   - Không đọc/inline Base64; chỉ dùng các asset objects đã được engine tạo sẵn.
*/
(function(){
'use strict';
var KEY='kthm2_arena_v3',root=null,canvas=null,ctx=null,raf=0,state=null,busy=false,current=null,paused=false,speed=1,startedAt=0,elapsed=0,currentOpponents=[];
var W=0,H=0,DPR=1;
function esc(s){return String(s==null?'':s).replace(/[&<>"']/g,function(c){return({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'})[c]})}
function num(v,d){v=Number(v);return isFinite(v)?v:d}
function load(){try{state=JSON.parse(localStorage.getItem(KEY)||'null')}catch(e){state=null}if(!state||typeof state!=='object')state={points:1000,wins:0,losses:0,streak:0,season:1,day:'',today:0,lastBattle:null};var d=new Date().toISOString().slice(0,10);if(state.day!==d){state.day=d;state.today=0;save()}}
function save(){try{localStorage.setItem(KEY,JSON.stringify(state))}catch(e){}}
function pname(){try{return (typeof PS!=='undefined'&&PS[cur]&&(PS[cur].nm||PS[cur].name))||(typeof pn!=='undefined'&&pn)||'Đạo Hữu'}catch(e){return 'Đạo Hữu'}}
function realm(){try{return typeof ZC!=='undefined'&&ZC.nm?ZC.nm():'Tu sĩ'}catch(e){return 'Tu sĩ'}}
function myPower(){try{return Math.max(1,Math.round(num(typeof atk==='function'?atk():100,100)*5+num(typeof df==='function'?df():50,50)*.55+num(typeof mx==='function'?mx():500,500)*.08))}catch(e){return 100}}
function skillSet(ci,br){try{var c=CHR[ci],b=c&&c.br&&br>=0?c.br[br]:null;return (b&&b.b?b.b:c.k||[]).concat(b&&b.k?b.k:[])}catch(e){return[]}}
function heroInfo(){var ci=typeof cur==='number'?cur:0,br=0;try{br=PS[ci]&&PS[ci].br>=0?PS[ci].br:0}catch(e){}return{ci:ci,br:br,c:CHR[ci]||CHR[0],skills:skillSet(ci,br)}}
function opponents(){var p=myPower(),out=[],names=['Huyền Vũ Kiếm Tôn','Thanh Liên Tiên Tử','Ma Đạo Cuồng Nhân','Thiên Cơ Đạo Nhân','U Minh Thánh Nữ','Cửu Thiên Kiếm Khách'];for(var i=0;i<5;i++){var ci=i%Math.max(1,CHR.length),br=(i+state.season)%2,mul=.84+i*.08+(Math.random()-.5)*.08;out.push({id:i,n:names[(i+state.season)%names.length],pw:Math.max(100,Math.round(p*mul)),lv:Math.max(1,Math.round(num(typeof P!=='undefined'&&P.lv,1)*(.9+i*.04))),rank:Math.max(1,Math.round(50+i*18)),ci:ci,br:br,skills:skillSet(ci,br)})}return out}
function combatStats(side,pw,ci,br){var h=num(typeof mx==='function'?mx():500,500);if(side==='op')h=Math.max(100,Math.round(h*(pw/myPower())*(.92+Math.random()*.16)));var atkBase=Math.max(8,pw*.18);return{hp:h,max:h,atk:atkBase,mp:100,maxMp:100,ci:ci,br:br,cd:[],alive:true}}
function skillDamage(actor,k){var mult=Math.max(.1,num(k&&k[5],1));var d=Math.max(1,Math.round(actor.atk*mult*(.78+Math.random()*.44)));return d}
function chooseSkill(actor,skills,t){for(var i=skills.length-1;i>=0;i--){var k=skills[i];if(!k)continue;var mp=Math.max(0,num(k[2],0)),cd=num(actor.cd[i],0);if(cd<=t&&actor.mp>=mp){return{i:i,k:k}}}return null}
function scheduleBattle(mePower,op){var hero=heroInfo(),me=combatStats('me',mePower,hero.ci,hero.br),en=combatStats('op',op.pw,op.ci,op.br),ms=hero.skills,os=op.skills,events=[],t=1.0,round=0,meLast=-99,opLast=-99;
  while(me.hp>0&&en.hp>0&&round<36){round++;var turnMe=round%2===1,actor=turnMe?me:en,target=turnMe?en:me,skills=turnMe?ms:os,sel=chooseSkill(actor,skills,t),k=sel?sel.k:['Đánh thường','⚔️',0,1,0,1],idx=sel?sel.i:-1;
    var name=turnMe?pname():op.n,icon=k[1]||'⚔️',d=0,heal=0,buff=false;
    if(idx>=0){actor.mp=Math.max(0,actor.mp-num(k[2],0));actor.cd[idx]=t+Math.max(.7,num(k[3],1)/100);var typ=num(k[4],0);if(typ===3||typ===10){heal=Math.round(actor.max*.12*Math.max(1,num(k[5],1)));actor.hp=Math.min(actor.max,actor.hp+heal);buff=true}else if(typ===6){buff=true;d=skillDamage(actor,k)*.7}else if(typ===9){buff=true}else{d=skillDamage(actor,k)}}else d=Math.max(1,Math.round(actor.atk*(.85+Math.random()*.3)));
    if(d>0){target.hp=Math.max(0,target.hp-d)}
    var at=t;events.push({at:at,side:turnMe?'me':'op',skill:k[0]||'Đánh thường',icon:icon,d:d,heal:heal,me:Math.max(0,me.hp),op:Math.max(0,en.hp),text:name+' dùng '+(k[0]||'Đánh thường')+(d?' · -'+d+' HP':'')+(heal?' · +'+heal+' HP':'')});
    if(target.hp<=0)break;
    t+=.72;meLast=turnMe?t:meLast;opLast=turnMe?opLast:t;
    actor.mp=Math.min(actor.maxMp,actor.mp+10);
  }
  var win=en.hp<=0&&me.hp>0;return{win:win,round:round,meMax:me.max,opMax:en.max,meHp:Math.max(0,me.hp),opHp:Math.max(0,en.hp),events:events,meCi:hero.ci,meBr:hero.br,opCi:op.ci,opBr:op.br}
}
function reward(win){var pts=win?18:7;state.points=Math.max(0,state.points+(win?pts:-12));if(win){state.wins++;state.streak++;try{gold=(gold|0)+250+state.streak*20;frag=(frag|0)+(state.streak%3===0?1:0)}catch(e){}}else{state.losses++;state.streak=0}state.today++;state.last=Date.now();save();try{if(typeof sv==='function')sv()}catch(e){}return pts}
function rank(){return Math.max(1,Math.round(1200-Math.max(0,state.points-1000)*.9))}
function stop(){if(raf){cancelAnimationFrame(raf);raf=0}}
function resize(){if(!canvas)return;DPR=Math.min(window.devicePixelRatio||1,2);W=Math.max(1,canvas.clientWidth||window.innerWidth||320);H=Math.max(1,canvas.clientHeight||window.innerHeight||240);canvas.width=Math.max(1,Math.round(W*DPR));canvas.height=Math.max(1,Math.round(H*DPR));ctx=canvas.getContext('2d');if(ctx)ctx.setTransform(DPR,0,0,DPR,0,0)}
function rr(x,y,w,h,r){w=Math.max(0,num(w,0));h=Math.max(0,num(h,0));r=Math.max(0,num(r,0));var q=Math.min(r,w/2,h/2);ctx.beginPath();ctx.moveTo(x+q,y);ctx.arcTo(x+w,y,x+w,y+h,q);ctx.arcTo(x+w,y+h,x,y+h,q);ctx.arcTo(x,y+h,x,y,q);ctx.arcTo(x,y,x+w,y,q);ctx.closePath()}
function text(t,x,y,size,col,align){ctx.fillStyle=col||'#fff';ctx.font='600 '+size+'px system-ui,-apple-system,Segoe UI,sans-serif';ctx.textAlign=align||'center';ctx.textBaseline='middle';ctx.fillText(String(t),x,y)}
function safeImg(im){return im&&im.naturalWidth>0&&im.naturalHeight>0}
function getSprite(ci){try{var r=RIGI[ci%RIGI.length];return r&&r.base&&r.base.im}catch(e){return null}}
function getWeapon(ci,br,tier){try{var c=CHR[ci],typ=c.t; tier=Math.max(0,Math.min(3,tier|0));if(typ==='w')return WPI[(br?1:0)*4+tier];if(typ==='m')return (br?WXI.staff:WXI.book)[tier];if(typ==='a')return (br?WXI.dagger:WXI.bow)[tier]}catch(e){}return null}
function drawFighter(f,x,y,flip,phase,attack,hit){var im=getSprite(f.ci),r=null;try{r=RIGI[f.ci%RIGI.length]}catch(e){};ctx.save();ctx.translate(x,y);ctx.scale(flip?-1:1,1);if(hit){ctx.globalAlpha=.72+.28*Math.sin(phase*25)}var bob=Math.sin(phase*4)*3;ctx.fillStyle='rgba(0,0,0,.35)';ctx.beginPath();ctx.ellipse(0,4,42,10,0,0,Math.PI*2);ctx.fill();if(safeImg(im)){var hh=Math.min(250,H*.34),ww=hh*(r.W/r.H);ctx.drawImage(im,-ww/2,-hh+bob,ww,hh)}else{ctx.fillStyle='#b88';ctx.beginPath();ctx.arc(0,-70,28,0,Math.PI*2);ctx.fill();ctx.fillRect(-24,-45,48,80)}var wi=getWeapon(f.ci,f.br,0);if(safeImg(wi)){var wl=75,wwi=wl*wi.naturalWidth/wi.naturalHeight;ctx.save();ctx.translate((attack?28:18),-95+bob);ctx.rotate((attack?(phase<.45?-1.2:.6):-.35)*(flip?-1:1));ctx.drawImage(wi,-wwi/2,-wl/2,wwi,wl);ctx.restore()}if(attack){ctx.globalCompositeOperation='lighter';ctx.strokeStyle=f.color||'#8ee';ctx.shadowColor=f.color||'#8ee';ctx.shadowBlur=16;ctx.globalAlpha=.75*(1-Math.min(1,phase));ctx.lineWidth=7;ctx.beginPath();ctx.arc(flip?-35:35,-92,54,flip?-.8:2.34,flip?-.8+2.3:2.34+2.3);ctx.stroke();ctx.globalAlpha=.9;ctx.beginPath();ctx.arc(flip?-38:38,-92,20,0,Math.PI*2);ctx.stroke()}ctx.restore()}
function drawBackground(now){var g=ctx.createLinearGradient(0,0,0,H);g.addColorStop(0,'#07101e');g.addColorStop(.55,'#241719');g.addColorStop(1,'#070504');ctx.fillStyle=g;ctx.fillRect(0,0,W,H);ctx.fillStyle='rgba(170,210,255,.09)';ctx.beginPath();ctx.arc(W*.5,H*.24,Math.min(W,H)*.12,0,Math.PI*2);ctx.fill();ctx.fillStyle='#30221d';ctx.beginPath();ctx.moveTo(0,H*.72);ctx.lineTo(W*.18,H*.48);ctx.lineTo(W*.34,H*.69);ctx.lineTo(W*.52,H*.45);ctx.lineTo(W*.72,H*.7);ctx.lineTo(W,H*.5);ctx.lineTo(W,H);ctx.lineTo(0,H);ctx.fill();ctx.fillStyle='#3c2920';ctx.fillRect(0,H*.72,W,H*.28);for(var i=0;i<8;i++){var x=W*(i/7),h=28+(i%3)*18;ctx.fillStyle='rgba(255,170,80,.18)';ctx.fillRect(x-3,H*.72-h,6,h);ctx.beginPath();ctx.arc(x,H*.72-h,7,0,Math.PI*2);ctx.fill()}}
function drawHp(f,x,y,align,name,skill){var bw=Math.min(260,W*.32),bx=align==='left'?x:x-bw,by=y;ctx.fillStyle='rgba(0,0,0,.65)';rr(bx,by,bw,28,7);ctx.fill();ctx.fillStyle='#f0d6a0';text(name,align==='left'?bx+8:bx+bw-8,by+7,12,'#f5dfb0',align==='left'?'left':'right');ctx.fillStyle='#351414';rr(bx+6,by+14,bw-12,8,4);ctx.fill();ctx.fillStyle='#63d68a';rr(bx+6,by+14,(bw-12)*Math.max(0,Math.min(1,f.hp/f.max)),4,4);ctx.fill();if(skill)text(skill,align==='left'?bx+8:bx+bw-8,by+38,11,'#d8d0c0',align==='left'?'left':'right')}
function renderFrame(now){if(!root||!canvas||!current||!ctx)return;var b=current.b,op=current.op;if(!paused)elapsed=Math.max(0,now-startedAt);var t=elapsed/1000*speed,evs=b.events||[],idx=0;while(idx<evs.length&&evs[idx].at<=t)idx++;var last=idx?evs[idx-1]:null,prev=idx>1?evs[idx-2]:null,phase=last?Math.max(0,Math.min(1,(t-last.at)/.55)):0;drawBackground(now);var meHp=last?last.me:b.meMax,opHp=last?last.op:b.opMax;var me={hp:meHp,max:b.meMax,ci:b.meCi,br:b.meBr,color:(CHR[b.meCi]||{}).c||'#8ee'},en={hp:opHp,max:b.opMax,ci:b.opCi,br:b.opBr,color:(CHR[b.opCi]||{}).c||'#f88'};var mx=W*.28,ox=W*.72;var attack=last&&phase<1,hit=last&&last.d>0&&phase>.35&&phase<.65;drawFighter(me,mx,H*.73,false,now/1000,attack&&last.side==='me',hit&&last.side==='op');drawFighter(en,ox,H*.73,true,now/1000,attack&&last.side==='op',hit&&last.side==='me');drawHp(me,mx-25,22,'left',pname(),last&&last.side==='me'?last.icon+' '+last.skill:'');drawHp(en,ox+25,22,'right',op.n,last&&last.side==='op'?last.icon+' '+last.skill:'');if(last&&last.d){text('-'+last.d,last.side==='me'?ox-35:mx+35,H*.43,24,last.side==='me'?'#ffd46b':'#ff8c8c')}if(last&&last.heal){text('+'+last.heal,last.side==='me'?mx:ox,H*.37,18,'#7fe08a')}var log=evs.slice(Math.max(0,idx-3),idx);ctx.fillStyle='rgba(8,6,5,.82)';rr(W*.1,H*.52,W*.8,Math.min(105,20+log.length*25),10);ctx.fill();for(var i=0;i<log.length;i++)text(log[i].icon+' '+log[i].text,W*.5,H*.55+i*25,11,i===log.length-1?'#ffe29b':'#c8bba5');ctx.fillStyle='rgba(0,0,0,.45)';rr(W*.08,H-58,W*.84,42,10);ctx.fill();text('1x',W*.20,H-37,11,speed===1?'#ffe29b':'#aaa');text('2x',W*.5,H-37,11,speed===2?'#ffe29b':'#aaa');text('4x',W*.8,H-37,11,speed===4?'#ffe29b':'#aaa');if(!evs.length){finishBattle();return}if(idx>=evs.length&&t>evs[evs.length-1].at+1.2){finishBattle();return}raf=requestAnimationFrame(renderFrame)}
function showScene(op,b,isReplay){stop();root.classList.add('on');resize();if(!W||!H||!ctx){setTimeout(function(){resize();showScene(op,b,isReplay)},40);return}root.classList.remove('result');var panel=root.querySelector('.arena-result');if(panel)panel.style.display='none';paused=false;speed=1;elapsed=0;current={op:op,b:b,isReplay:!!isReplay};startedAt=performance.now();raf=requestAnimationFrame(renderFrame)}
function finishBattle(){if(!current)return;stop();busy=false;var op=current.op,b=current.b,isReplay=current.isReplay,pts=isReplay&&state.lastBattle?state.lastBattle.pts:reward(b.win);if(!isReplay){state.lastBattle={op:op,win:b.win,events:b.events,meMax:b.meMax,opMax:b.opMax,pts:pts,meCi:b.meCi,meBr:b.meBr,opCi:b.opCi,opBr:b.opBr,at:Date.now()};save()}showResult(op,b,pts,isReplay)}
function showResult(op,b,pts,isReplay){root.classList.add('result');var panel=root.querySelector('.arena-result');if(!panel)return;panel.style.display='flex';panel.innerHTML='<div class="result-card"><div class="result-title '+(b.win?'win':'lose')+'">'+(b.win?'🏆 CHIẾN THẮNG':'💀 THẤT BẠI')+'</div><div class="result-line"><b>'+esc(pname())+'</b> ⚔️ <b>'+esc(op.n)+'</b></div><div class="result-sub">'+(isReplay?'🔄 Xem lại — không nhận lại thưởng':(b.win?'+'+pts+' điểm · 🎁 Phần thưởng đã nhận':'-12 điểm · thử lại lần sau'))+'</div><div class="result-log">'+(b.events||[]).map(function(e){return '<div>'+esc(e.icon+' '+e.text)+'</div>'}).join('')+'</div><div class="result-actions"><button id="arena-result-back">↩ Đấu Trường</button><button id="arena-result-replay">🔄 Xem lại trận</button></div></div>';panel.querySelector('#arena-result-back').onclick=function(){openLobby()};panel.querySelector('#arena-result-replay').onclick=function(){showScene(op,b,true)}}
function build(){root=document.createElement('div');root.id='arena-scene';root.innerHTML='<canvas id="arena-canvas"></canvas><div class="arena-topbar"><button id="arena-exit">✕ Rời đấu trường</button><span>⚔️ Đấu Trường Linh Giới · Skill thật</span><span>'+esc(realm())+'</span></div><div class="arena-result"></div>';document.body.appendChild(root);canvas=root.querySelector('#arena-canvas');ctx=canvas.getContext('2d');root.querySelector('#arena-exit').onclick=function(){if(busy&&!confirm('Rời trận? Trận này sẽ không nhận thưởng.'))return;busy=false;current=null;stop();root.classList.remove('on','result')};window.addEventListener('resize',resize);resize();canvas.addEventListener('click',function(e){if(!current)return;var r=canvas.getBoundingClientRect(),x=e.clientX-r.left,y=e.clientY-r.top;if(y>H-75){if(x>W*.68)speed=4;else if(x>W*.36)speed=2;else speed=1}})}
function open(){load();if(!root){build()}root.classList.add('on');openLobby()}
function openLobby(){load();root.classList.remove('result');var c=root.querySelector('.arena-result');c.style.display='flex';var ops=opponents(),left=Math.max(0,10-(state.today|0));currentOpponents=ops;c.innerHTML='<div class="arena-lobby"><div class="lobby-title">⚔️ ĐẤU TRƯỜNG LINH GIỚI</div><div class="lobby-info"><b>'+esc(pname())+'</b><br><small>'+esc(realm())+' · Lực chiến '+myPower().toLocaleString()+' · Điểm '+state.points+' · Hạng #'+rank()+'</small><br><small>🏆 '+state.wins+' thắng · '+state.losses+' thua · 🔥 Chuỗi '+state.streak+' · Lượt hôm nay '+left+'/10</small></div><div id="arena-opps"></div><div class="lobby-note">Chọn đối thủ → <b>⚔️ THÁCH ĐẤU</b> → trận bắt đầu ngay bằng <b>ảnh nhân vật thật + kỹ năng thật</b>.</div></div>';var list=c.querySelector('#arena-opps');list.innerHTML=ops.map(function(o){var sk=o.skills&&o.skills.length?o.skills.slice(-4).map(function(k){return k[1]+' '+k[0]}).join(' · '):'Đánh thường';return '<div class="arena-op"><div><b>'+esc(o.n)+'</b><small>Lv '+o.lv+' · Lực chiến '+o.pw.toLocaleString()+'</small><small>'+esc(sk)+'</small></div><button data-id="'+o.id+'" '+(left<=0?'disabled':'')+'>⚔️ THÁCH ĐẤU</button></div>'}).join('');list.querySelectorAll('button[data-id]').forEach(function(btn){btn.onclick=function(){challenge(+btn.getAttribute('data-id'))}})}
function challenge(id){load();if(busy)return;if(state.today>=10){alert('Đã hết 10 lượt Đấu Trường hôm nay.');return}var o=currentOpponents.find(function(x){return x.id===id});if(!o)return;var b=scheduleBattle(myPower(),o);busy=true;showScene(o,b,false)}
function close(){busy=false;current=null;stop();if(root)root.classList.remove('on','result')}
window.Arena={open:open,close:close,save:save,load:load,api:{challenge:challenge}};
function addButton(){if(document.getElementById('arena-btn'))return;var b=document.createElement('button');b.id='arena-btn';b.className='sb';b.title='Đấu Trường';b.innerHTML='⚔️<small>Đấu</small>';b.onclick=open;document.body.appendChild(b)}
function styles(){if(document.getElementById('arena-v4-style'))return;var st=document.createElement('style');st.id='arena-v4-style';st.textContent='#arena-scene{position:fixed;inset:0;z-index:99999;display:none;background:#080606;color:#fff;font-family:system-ui,-apple-system,Segoe UI,sans-serif}#arena-scene.on{display:block}#arena-canvas{position:absolute;inset:0;width:100%;height:100%;touch-action:none}#arena-scene .arena-topbar{position:absolute;top:0;left:0;right:0;height:44px;display:flex;align-items:center;justify-content:space-between;padding:0 10px;background:linear-gradient(180deg,rgba(7,7,10,.92),rgba(7,7,10,.15));font-size:12px;color:#e9d39c;pointer-events:none}#arena-exit{pointer-events:auto;background:rgba(45,31,20,.9);border:1px solid #9e793e;border-radius:6px;color:#f2e4bd;padding:6px 9px;font:inherit}.arena-result{position:absolute;inset:0;display:flex;align-items:center;justify-content:center;background:rgba(0,0,0,.62);padding:18px;z-index:5}.arena-result .result-card{width:min(650px,92vw);max-height:84vh;overflow:auto;background:linear-gradient(180deg,#1b120d,#0c0908);border:1px solid #b08a49;border-radius:12px;box-shadow:0 20px 80px #000;padding:18px}.arena-result .result-title{text-align:center;font-size:24px;font-weight:800;margin-bottom:10px}.arena-result .win{color:#ffd86a}.arena-result .lose{color:#ff9188}.result-line{text-align:center;color:#e9d8b1}.result-sub{text-align:center;margin:9px 0;color:#c9b997}.result-log{background:#080605;border-radius:8px;padding:10px;font-size:11px;line-height:1.55;max-height:200px;overflow:auto}.result-actions{display:flex;justify-content:center;gap:8px;margin-top:12px}.result-actions button,.arena-op button{background:#5c431f;color:#f5e7be;border:1px solid #b18b4c;border-radius:6px;padding:8px 12px;font:inherit}.arena-lobby{width:min(650px,94vw);max-height:84vh;overflow:auto;background:rgba(16,10,8,.96);border:1px solid #b18b4c;border-radius:12px;padding:16px;box-shadow:0 20px 90px #000}.lobby-title{text-align:center;font-size:20px;font-weight:800;color:#ffd86a;margin-bottom:10px}.lobby-info{text-align:center;line-height:1.55;color:#e9d9b6;margin-bottom:10px}.arena-op{display:flex;justify-content:space-between;gap:10px;align-items:center;background:#19100c;border:1px solid #5c4327;border-radius:8px;padding:9px;margin:7px 0}.arena-op b,.arena-op small{display:block}.arena-op small{color:#bcae91;margin-top:3px;line-height:1.35}.arena-op button{white-space:nowrap}.arena-op button:disabled{opacity:.45}.lobby-note{text-align:center;font-size:11px;color:#bcae91;margin-top:10px;line-height:1.5}@media(max-width:640px){.arena-topbar span:last-child{display:none}.arena-lobby{padding:12px}.arena-op{padding:8px}.arena-op button{padding:7px 9px;font-size:11px}.arena-op small{font-size:10px}}';document.head.appendChild(st)}
function init(){load();styles();addButton()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();
